---
- name: Install Docker
  hosts: "{{ env }}"
  become: true
  roles:
    - role: geerlingguy.docker

- name: Deploy bot configuration
  hosts: "{{ env }}"
  become: true
  roles:
    - role: deploy-config
      vars:
        deploy_config_name: bot
        deploy_target_path: /opt/bot
